name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: create build folder
      run: mkdir build
    
    # - name: create build folder
    #   run: cd build
    
    - name: configure CMake
      run: cmake -G "MinGW Makefiles" . -B build
      run: cd build
    
    - name: make check
      run: make
    
    # - name: make distcheck
    #   run: make distcheck
